export const data = [
    {
        id:1,
        dupto: "Discount up to",
        percet: "20% - 65%",
        valid: "Valid for 4 mins",
        shopno: "Shop no- 3",
        islike:false,
        dislike:false,
        isredeem:false,
        redcode:'ZA76AE',
        stepsaway:"10-15 steps away",
        img:require('../assets/icons/bata.png'),
        

    },
    {
        id:2,
        dupto: "Discount up to",
        percet: "30% -50%",
        valid: "Valid for 8 mins",
        shopno: "Shop no- 6",
        islike:false,
        dislike:false,
        isredeem:false,
        redcode:'KIJ37Y',
        stepsaway:"10-15 steps away",
        img:require('../assets/icons/rebook.png'),
    },
    {
        id:3,
        dupto: "Discount up to",
        percet: "20% - 40%",
        valid: "Valid for 5 mins",
        shopno: "Shop no- 2",
        islike:false,
        dislike:false,
        isredeem:false,
        redcode:'PKD73H',
        stepsaway:"10-15 steps away",
        img:require('../assets/icons/adidas.png'),
    },
    {
        id:4,
        dupto: "Discount up to",
        percet: "25% - 60%",
        valid: "Valid for 15 mins",
        shopno: "Shop no- 1",
        islike:false,
        dislike:false,
        isredeem:false,
        redcode:'E2FQJ9',
        stepsaway:"10-15 steps away",
        img:require('../assets/icons/domi.png'),
    },
    {
        id:5,
        dupto: "Discount up to",
        percet: "40% - 55%",
        valid: "Valid for 15 mins",
        shopno: "Shop no- 3",
        islike:false,
        dislike:false,
        isredeem:false,
        redcode:'N3I33I',
        stepsaway:"10-15 steps away",
        img:require('../assets/icons/nike.png'),
    },
    {
        id:6,
        dupto: "Discount up to",
        percet: "30% - 65%",
        valid: "Valid for 15 mins",
        shopno: "Shop no- 2",
        islike:false,
        dislike:false,
        isredeem:false,
        redcode:'MD73HD',
        stepsaway:"10-15 steps away",
        img:require('../assets/icons/mcdd.png'),
    },
    {
        id:7,
        dupto: "Discount up to",
        percet: "10% - 30%",
        valid: "Valid for 15 mins",
        shopno: "Shop no- 2",
        islike:false,
        dislike:false,
        isredeem:false,
        redcode:'OPE3J2',
        stepsaway:"10-15 steps away",
        img:require('../assets/icons/liberty.png'),
    },
   

]